version: '3.8'

services:
    db:
        image: "postgres"
        env_file:
            - database.env 
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        ports: 
            - "5432:5432"
        networks:
            - nesjs-network
    prod:
        depends_on: 
            - db
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
volumes:
    database_data:
        driver: local
networks:
    nesjs-network: